apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-connection
          key: db_h.txt
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: db-connection
          key: db_p.txt
