apiVersion: batch/v1
kind: Job
metadata:
  name: pi-calc-job
spec:
  template:
    spec:
      containers:
      - name: pi-calc-container
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
