apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-traffic
spec:
  podSelector:
    matchLabels:
      run: nginx-pod
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: jumppod
